name = "sand"
description = "Falling sand simulation using Braillart"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["alejandro@mosteo.com"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["demo", "sand", "simulation", "braille", "art"]

executables = ["sand"]

[[depends-on]]
ansiada = "^1.1.0"
braillart = "*"

[[pins]]
braillart = { path='../..' }
