name = "gen_chart"
description = ""
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["gen_chart"]

[test]
runner = "alire"

[[depends-on]]
braillart = "~0.1.0-dev"

[[pins]]
braillart = { path='../..' }
