name: build

on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest     # x86_64 Linux
          - ubuntu-24.04-arm  # ARM64 Linux
          - macos-13          # Intel macOS
          - macos-latest      # ARM64 macOS
          - windows-latest    # x86_64 Windows
          # - windows-11-arm    # ARM64 Windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Alire
        uses: alire-project/setup-alire@v5
        with:
          version: nightly

      - name: Build project
        run: alr build
